### PR TITLE
Add targets for Xenial remove EOLs

### PR DESCRIPTION
**Pull request by lloesche**

### CODE REVIEW

**Comment by lingmann** [comment]
Wily is end-of-life as of July 2016... at this point I'd be inclined to just add 16.04 packages. Thoughts?

**Comment by lloesche** [comment]
I think we could go about this two ways:
1) We also have Fedora 20, 21 and 22 as well as Debian Wheezy in here. Platforms that we don't support on our repo server and never test. Since Marathon and Chronos run on the JVM with little dependencies to the OS it stands to reason that it'll very likely work as long as the init scripts are sane. In which case I would have no problem leaving EOL distributions in here hoping that it'll be useful for someone else. If something breaks it's up to the community that uses these targets to fix the distributions that we don't test and support ourselves. It's all open source after all.

2) We regularly remove old distributions that we don't officially support on our repo server in which case we should remove the targets fedora20, fedora21, fedora22, debian-wheezy-77, ubuntu-vivid and ubuntu-wily.

I'm fine with either one.

**Comment by lloesche** [comment]
@lingmann updated

**Comment by lingmann** [comment]
👍

**Pull request merged**
